global:
    scrape_interval: 10s
    evaluation_interval: 10s
    scrape_timeout: 10s
    external_labels:
      monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'airflow'
    static_configs:
      - targets: ['statsd-exporter:9102']

    tls_config:
      insecure_skip_verify: true